### PR TITLE
OP-7156 Update for product renaming and deem.com redesign

### PR DESCRIPTION
**Pull request by hunpin**
Due to the early 2015 Product Renaming exercise and the newly designed deem.com homepage, we need to make some updates to deem.com/developer, developer.offerengine.com, and all their sub-pages.

Changes to color style:
* All uses of #00BCFF in text and background coloring shall be changed to #32AA00 so that these pages match the deem.com redesign.

Changes to headers:
* The current logo graphic (which says "deemdeveloper") shall be changed to a generic Deem logo deem_logo_reg.png (attached).
* The 'Home' link shall remain unchanged.
* The 'Documentation' link shall remain unchanged.
* The 'Support' link shall direct to https://www.deem.com/programs/support.

Changes to footers:
* The 'Deem' link shall remain unchanged.
* A new link labeled 'Products' shall direct to https://www.deem.com/products/.
* The 'Save' link shall be removed.
* The 'Sell' link shall be removed.
* The 'Partner' link shall be removed.
* The 'Discover' link shall remain unchanged.
* The 'Develop' hypertext shall be relabeled to say 'Developers'.
* The 'About Us' link shall direct to https://www.deem.com/company/about.
* The 'Feedback' link shall direct to https://www.deem.com/programs/support. 

developer_offerengine_com1

developer_offerengine_com2

### CODE REVIEW

**Comment by hunpin** [comment]
@DTocher please review the changes.

**Comment by RealNobody** [comment]
:+1: 

Jenkins?

:ghost:

**Comment by DTocher** [comment]
:+1: from Product.

**Comment by LukeHammond** [comment]
:+1:

**Pull request merged**
